<a href="https://colab.research.google.com/github/Ang-Li-code/MAT422/blob/main/HW_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Concepts in Linear Algebra, Part 2

The following code will provide examples that demonstrate a few selected principles observed in the subjects of QR Decomposition, Least-Squares Problems, and Linear Regression.

This will be accomplished through generating random vectors and datasets to illustrate the principles observed in each topic.

## QR Decomposition

We have learned that through the Gram-Schmidt process, a matrix A can be decomposed into two matrices, Q and R, where A = QR.

The following code will validate the decomposition process. (Note that there may be round offs and the dot product of QR may be very close to, but not entirely equivalent, to A)


In [8]:
import random
import numpy as np

# Generates a random 3x3 matrix
def randomMatrix():
  x1 = random.randrange(0, 9)
  x2 = random.randrange(0, 9)
  x3 = random.randrange(0, 9)
  x4 = random.randrange(0, 9)
  x5 = random.randrange(0, 9)
  x6 = random.randrange(0, 9)
  x7 = random.randrange(0, 9)
  x8 = random.randrange(0, 9)
  x9 = random.randrange(0, 9)

  A = np.array([[x1, x2, x3],
               [x4, x5, x6],
               [x7, x8, x9]])

  return A

# Create a random 3x3 matrix
matrixA = randomMatrix()
print("Matrix A: \n", matrixA)

# Perform Q R decompisition on the matrix
q, r = np.linalg.qr(matrixA)

print("\nQ: \n", q)
print("\nR: \n", r)

# Validate that A = QR
newA = np.dot(q, r)
print("\nQR = \n", newA)



Matrix A: 
 [[3 2 6]
 [7 5 0]
 [1 0 0]]

Q: 
 [[-0.39056673  0.11884567 -0.91287093]
 [-0.91132238 -0.19015308  0.36514837]
 [-0.13018891  0.97453451  0.18257419]]

R: 
 [[-7.68114575 -5.33774535 -2.3434004 ]
 [ 0.         -0.71307403  0.71307403]
 [ 0.          0.         -5.47722558]]

QR = 
 [[ 3.00000000e+00  2.00000000e+00  6.00000000e+00]
 [ 7.00000000e+00  5.00000000e+00  1.33541675e-15]
 [ 1.00000000e+00  2.80189643e-16 -1.51866092e-15]]


## Least-Squares Problems

We learned that for the equation Ax = b, in an overdetermined case, where A is an nxm matrix, n > m, and b is a vector of dimension n, there may not be a possible solution for x, and thus we seek to find a vector $x^*$ that minimizes Ax = b

In order to solve for $x^*$, we may either utilize the invertible nature of $A^TA$ or $QR$ decomposition, where $(A^TA)^{-1}A^Tb = x^*$ or $R^{-1}Q^Tb = x^*$, respectively.

Since it is very difficult to show that $x^*$ is the best approximation for Ax = b, the following code will only display the results of each method, and show why one may be more preferable to the other.

In [22]:
def randomVector():
  x1 = random.randrange(0, 9)
  x2 = random.randrange(0, 9)
  x3 = random.randrange(0, 9)

  vector = np.array([[x1], [x2], [x3]])

  return vector

def inverse_x_star(A, b):
  A_t = np.transpose(A)
  ans = np.linalg.inv(A_t * A) * A_t * b

  return ans

def QR_x_star(A, b):
  q, r = np.linalg.qr(A)
  q_t = np.transpose(q)
  ans = np.dot(np.linalg.inv(r),  q_t, b)

  return ans

# Generate a random 3x3 matrix and a random 3x1 vector
A = randomMatrix()
b = randomVector()

print("Matrix A: \n", A)
print("\nVector b: \n", b)

# Generate x star using the two methods mentioned above
inv_x_star = inverse_x_star(A, b)
qr_x_star = QR_x_star(A, b)

print("X star using inverse of A: ", inv_x_star)
print("X star using QR of A: ", qr_x_star)

Matrix A: 
 [[1 6 1]
 [3 3 8]
 [1 7 1]]

Vector b: 
 [[3]
 [8]
 [4]]


ValueError: output array is not acceptable (must have the right datatype, number of dimensions, and be a C-Array)