<a href="https://colab.research.google.com/github/Ang-Li-code/MAT422/blob/main/HW_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Concepts in Linear Algebra, Part 3

The following code will provide examples that demonstrate principles observed in the subjects of singular value decomposition, low rank matrix approximations, and principal component analysis.

This will be accomplished by showing how these techniques are performed on sample datasets and an additional example of image compression utilizing low rank matrix approximations

## Singular Value Decomposition

We learned that for a given n x m matrix $A$, it can be decomposed into 3 separate matrices, $U$ (m x m), $s$ (m x n), and $V$ (n x n)

The following code will generate a random matrix $A$, perform singular value decomposition on it, and show that $U * S * V = A$

In [30]:
import numpy as np
import random

def create_sigma(s, n, m):
  sigma = np.eye(n, m)

  for i in range(min(n, m)):
    sigma[i][i] = s[i]

  return sigma

n = random.randrange(2, 10)
m = random.randrange(2, 10)

A = np.random.randint(0, 100, size=(n, m))

print("Matrix A", A.shape,":\n", A)

U, s, V = np.linalg.svd(A, full_matrices=True)

sigma = create_sigma(s, n, m)

print("\nU:", U.shape, "\n", U)
print("s:", sigma.shape, "\n", sigma)
print("V:", V.shape, "\n", V)

newA = U.dot(sigma.dot(V))

print("\nU * s * V = \n", newA)

Matrix A (8, 5) :
 [[73 77 47 28 48]
 [46 63 65 54 95]
 [ 2 53  4 74 48]
 [40 93 35 79 20]
 [99 36 18 82 78]
 [23 31 80 58 40]
 [73 69 42 43 40]
 [55 85  5 49 80]]

U: (8, 8) 
 [[-0.35371499  0.06499749  0.28133989  0.47714357  0.17039744  0.23902837
  -0.4945308  -0.48281709]
 [-0.41321683 -0.2120438   0.25917982 -0.32005499  0.49553907 -0.60049157
   0.05744443 -0.07232524]
 [-0.2520548  -0.12832145 -0.63270234 -0.36255596  0.03603327  0.2478975
   0.12857391 -0.55584178]
 [-0.35627236 -0.2879096  -0.47244965  0.41468181 -0.34973449 -0.41535716
  -0.20684268  0.23955941]
 [-0.41494679  0.53560604  0.18734704 -0.40521332 -0.55732354 -0.08236737
  -0.15559439  0.00671225]
 [-0.27889099 -0.65395721  0.2954914  -0.24024955 -0.19607485  0.47646566
  -0.06360229  0.28286859]
 [-0.34687684  0.06213609  0.18422929  0.37916779 -0.13527507  0.07277658
   0.8149434  -0.10187444]
 [-0.37867053  0.36477344 -0.27165832  0.02837414  0.48418893  0.33045458
  -0.02089648  0.55215018]]
s: (8, 5) 
 [[3

# Low Rank Matrix Approximations

We learned that by utilizing singular value decompositions, we can obtain the best $k$ rank approximation, $A_k$, for any given matrix $A$, where $A_K = \sum_{n = 1}^k \sigma_ju_jv^T_j$ and $\sigma_j$, $u_j$, and $v^T_j$ correspond to the singular values of $A$ (values in the diagonals of s in singular value decompositions), and the column vectors of $U$ and $V$, respectively.

The