<a href="https://colab.research.google.com/github/Ang-Li-code/MAT422/blob/main/HW_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Concepts in Linear Algebra, Part 1**

The following code will provide examples that demonstrate a few selected principles observed in the subjects of linear subspaces, orthogonality, the gram-schmidt progress, as well as eigenvalues and eigenvectors.

This will be accomplished through generating random vectors and demonstrating that they exhibit the properties described in each topic.

## Span

We learned that the span of a set of vectors is closed under vector addition, as well as scalar multiplication.

### Closure under vector addition

In [ ]:
import random
import numpy as np

# Returns a random vector in R3 with coordinate values between 0 and 9
def random3Dvector():
  x1 = random.randrange(0, 9)
  x2 = random.randrange(0, 9)
  x3 = random.randrange(0, 9)

  vector = np.array([x1, x2, x3])

  return vector

# Generate 3 random vectors and 2 sets of 3 random coefficients
vector1 = random3Dvector()
vector2 = random3Dvector()
vector3 = random3Dvector()

print("Vector1 = ", vector1)
print("Vector2 = ", vector2)
print("Vector3 = ", vector3)

alpha1 = random.randrange(0, 9)
alpha2 = random.randrange(0, 9)
alpha3 = random.randrange(0, 9)

print("\nalpha1 = ", alpha1)
print("alpha2 = ", alpha2)
print("alpha3 = ", alpha3)

beta1 = random.randrange(0, 9)
beta2 = random.randrange(0, 9)
beta3 = random.randrange(0, 9)

print("\nbeta1 = ", beta1)
print("beta2 = ", beta2)
print("beta3 = ", beta3)

# Generate 2 linear combinations of the previous 3 vectors
alphaVector = alpha1 * vector1 + alpha2 * vector2 + alpha3 * vector3
print("\nalphaVector = alpha1 * vector1 + alpha2 * vector2 + alpha3 * vector3  = ", alpha1, "*", vector1, "+", alpha2, "*", vector2, "+", alpha3, "*", vector3, "=", alphaVector)

betaVector = beta1 * vector1 + beta2 * vector2 + beta3 * vector3
print("betaVector = beta1 * vector1 + beta2 * vector2 + beta3 * vector3 = ", beta1, "*", vector1, "+", beta2, "*", vector2, "+", beta3, "*", vector3, "=", betaVector)

# Add the 2 new vectors and prove that it could also be generate via linear combination of the 3 original vectors
thetaVector = alphaVector + betaVector
print("\nthetaVector = alphaVector + betaVecotr = ", thetaVector)

deltaVector = (alpha1 + beta1) * vector1 + (alpha2 + beta2) * vector2 + (alpha3 + beta3) * vector3
print("deltaVector = (alpha1 + beta1) * vector1 + (alpha2 + beta2) * vector2 + (alpha3 + beta3) * vector3 = ", deltaVector)


Vector1 =  [5 2 2]
Vector2 =  [4 5 2]
Vector3 =  [4 5 5]

alpha1 =  8
alpha2 =  0
alpha3 =  4

beta1 =  4
beta2 =  7
beta3 =  7

alphaVector = alpha1 * vector1 + alpha2 * vector2 + alpha3 * vector3  =  8 * [5 2 2] + 0 * [4 5 2] + 4 * [4 5 5] = [56 36 36]
betaVector = beta1 * vector1 + beta2 * vector2 + beta3 * vector3 =  4 * [5 2 2] + 7 * [4 5 2] + 7 * [4 5 5] = [76 78 57]

thetaVector = alphaVector + betaVecotr =  [132 114  93]
deltaVector = (alpha1 + beta1) * vector1 + (alpha2 + beta2) * vector2 + (alpha3 + beta3) * vector3 =  [132 114  93]


### Closure under scalar multiplication


In [ ]:
# Generate 3 random scalars
alpha1 = random.randrange(0, 9)
alpha2 = random.randrange(0, 9)
alpha3 = random.randrange(0, 9)

print("\nalpha1 = ", alpha1)
print("alpha2 = ", alpha2)
print("alpha3 = ", alpha3)

# Generate a linear combination using the scalars
alphaVector = alpha1 * vector1 + alpha2 * vector2 + alpha3 * vector3
print("\nalphaVector = alpha1 * vector1 + alpha2 * vector2 + alpha3 * vector3  = ", alpha1, "*", vector1, "+", alpha2, "*", vector2, "+", alpha3, "*", vector3, "=", alphaVector)

# Perform scalar multiplication on the new vector
beta = random.randrange(2, 9)
print("\nbeta = ", beta)

betaVector = beta * alphaVector
print("betaVector = beta * alphaVector = ", beta, "*", alphaVector, "=", betaVector)

# Show that product of scalar multiplication is still a linear combination of the original 3 vectors
thetaVector = (beta * alpha1) * vector1 + (beta * alpha2) * vector2 + (beta * alpha3) * vector3
print("\nthetaVector = (beta * alpha1) * vector1 + (beta * alpha2) * vector2 + (beta * alpha3) * vector3 = ", thetaVector)


alpha1 =  1
alpha2 =  6
alpha3 =  3

alphaVector = alpha1 * vector1 + alpha2 * vector2 + alpha3 * vector3  =  1 * [8 3 2] + 6 * [2 8 5] + 3 * [7 2 4] = [41 57 44]

beta =  7
betaVector = beta * alphaVector =  7 * [41 57 44] = [287 399 308]

thetaVector = (beta * alpha1) * vector1 + (beta * alpha2) * vector2 + (beta * alpha3) * vector3 =  [287 399 308]


## Orthogonality

We have learned that the absolute value of the inner product of any two vectors cannot be greater than the product of their individual magnitudes.

(Note that in this code below, since the vectors are programmed to only contain components of positive values, we do not need to worry about calculating the absolute value of their inner product.)

In [ ]:
# This function calculates the inner product of 2 vectors (must be 3 dimensional)
def innerProduct(vec1, vec2):
  sum = 0
  for i in range(0, 3):
    sum += vec1[i] * vec2[i]
  return sum

# This function calculates the norm of a vector (must be 3 dimensional)
def norm(vec):
  sum = 0
  for i in range(0, 3):
    sum += np.power(vec[i], 2)
  return np.sqrt(sum)

# Generate 2 random vectors
vector1 = random3Dvector()
vector2 = random3Dvector()

print("Vector1 = ", vector1)
print("Vector2 = ", vector2)

# Calculate the norms of the 2 vectors
norm1 = norm(vector1)
norm2 = norm(vector2)

print("\nNorm of vector1 = ", norm1)
print("Norm of vector2 = ", norm2)

# Calculate the product of the norms of the 2 vectors
product_of_norms = norm1 * norm2
print("\nnorm1 * norm2 = ", product_of_norms)

# Calculate the inner product of the two vectors
inner = innerProduct(vector1, vector2)
print("\nInner Product = ", inner)


Vector1 =  [0 8 7]
Vector2 =  [7 6 0]

Norm of vector1 =  10.63014581273465
Norm of vector2 =  9.219544457292887

norm1 * norm2 =  98.00510190801293

Inner Product =  48


# The Gram-Schmidt Process
The code below will utilize the Gram-Schmidt algorithm to obtain orthonormal bases for random 3-dimensional vectors

(Note that approximations will be made so numbers close to 1 or 0 will be assumed to be 1 or 0, respectively)

In [ ]:
# This function turns a vector into a unit vector in the same direction (must be 3 dimensional)
def unitize(vector):
  magnitude = norm(vector)
  return vector / magnitude

# Generates 3 random vectors
print("Before Gram-Schmidt Process:\n")

vector1 = random3Dvector()
vector2 = random3Dvector()
vector3 = random3Dvector()

print("Vector1 = ", vector1)
print("Vector2 = ", vector2)
print("Vector3 = ", vector3)

# Performs the Gram-Schmidt process on the vectors
print("\nAfter Gram-Schmidt Process:\n")

q1 = unitize(vector1)
q2 = (vector2 - innerProduct(vector2, q1) * q1) / norm((vector2 - innerProduct(vector2, q1) * q1))
q3 = (vector3 - innerProduct(vector3, q1) * q1 - innerProduct(vector3, q2) * q2) / norm((vector3 - innerProduct(vector3, q1) * q1 - innerProduct(vector3, q2) * q2))

print("q1 = ", q1)
print("q2 = ", q2)
print("q3 = ", q3)

# Show that the 3 vectors are orthonormal
print("\nProof of orthonormality\n")

print("||q1|| = ", norm(q1))
print("||q2|| = ", norm(q2))
print("||q3|| = ", norm(q3))

print("\n<q1, q2> = ", innerProduct(q1, q2))
print("<q1, q3> = ", innerProduct(q1, q3))
print("<q2, q3> = ", innerProduct(q2, q3))


Before Gram-Schmidt Process:

Vector1 =  [6 1 5]
Vector2 =  [5 4 5]
Vector3 =  [7 0 1]

After Gram-Schmidt Process:

q1 =  [0.76200076 0.12700013 0.63500064]
q2 =  [-0.22606651  0.97105841  0.07706813]
q3 =  [ 0.60683505  0.20227835 -0.76865772]

Proof of orthonormality

||q1|| =  0.9999999999999999
||q2|| =  1.0
||q3|| =  0.9999999999999999

<q1, q2> =  2.1510571102112408e-16
<q1, q3> =  -5.551115123125783e-17
<q2, q3> =  -2.914335439641036e-16


# Eigenvalues and Eigenvectors

We learned that an n-th dimension matrix there can be at most n distinct eigenvalues.

The code below will demonstrate one sample matrix and it's eigenvalues, and then proceed to show that any random n-th dimension matrix will not have more than n distinct eigenvalues

In [ ]:
matrix1 = np.matrix("0, 1; -2, -3")
print("Matrix1 = \n", matrix1)

eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print("\nMatrix1 eigenvalues: \n", eigenvalues)

num_unique = len(np.unique(eigenvalues))

print("\nNumber of distinct eigenvalues:", num_unique)

matrix2 = np.matrix("2, 3, 1; 0, 1, 2; 0, 0, 1")
print("\nMatrix2 = \n", matrix2)

eigenvalues, eigenvectors = np.linalg.eig(matrix2)
print("\nMatrix2 eigenvalues: \n", eigenvalues)

num_unique = len(np.unique(eigenvalues))

print("\nNumber of distinct eigenvalues:", num_unique)

Matrix1 = 
 [[ 0  1]
 [-2 -3]]

Matrix1 eigenvalues: 
 [-1. -2.]

Number of distinct eigenvalues: 2

Matrix2 = 
 [[2 3 1]
 [0 1 2]
 [0 0 1]]

Matrix2 eigenvalues: 
 [2. 1. 1.]

Number of distinct eigenvalues: 2


In [ ]:
# Generates a random matrix of a certain dimension
def randomMatrix(dim):
  return np.random.rand(dim, dim)

num = random.randrange(2, 1000)
matrix3 = randomMatrix(num)

print("Dimensions: ", num)
print("\nMatrix: ", matrix3)

eigenvalues, eigenvectors = np.linalg.eig(matrix3)
num_eigenvalues = len(np.unique(eigenvalues))

print("\nNumber of distinct eigenvalues: ", num_eigenvalues)

Dimensions:  788

Matrix:  [[0.96188881 0.24134897 0.30895234 ... 0.15389396 0.53854705 0.21577385]
 [0.69697989 0.49018391 0.38093675 ... 0.02457207 0.51163625 0.24663968]
 [0.56618041 0.58203012 0.22089908 ... 0.47059275 0.16913762 0.79994516]
 ...
 [0.24832932 0.76310641 0.74966618 ... 0.02066669 0.52688818 0.5097684 ]
 [0.79428988 0.07488829 0.35891423 ... 0.27242904 0.9353194  0.79237587]
 [0.88897245 0.06814288 0.67664951 ... 0.18353218 0.49572634 0.24418963]]

Number of distinct eigenvalues:  788
